version: '3'

services:
  postgres:
    image: 'postgres:12.2-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    env_file:
      - '.env'
  api:
    depends_on:
      - postgres
      - mosquitto
    build:
      context: .
    volumes:
      - '.:/myapp'
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    command: 'bundle exec puma -C config/puma.rb'
  mosquitto:
    image: eclipse-mosquitto:1.6
    volumes:
      - mosquito:/mosquitto/data
      - mosquito:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  postgres:
  mosquito:
